netsh advfirewall firewall delete rule name="BLOCK_OW2_MENA_A"
netsh advfirewall firewall delete rule name="BLOCK_OW2_MENA_B"
netsh advfirewall firewall delete rule name="BLOCK_OW2_MENA_C"
netsh advfirewall firewall delete rule name="BLOCK_OW2_MENA_D"
netsh advfirewall firewall delete rule name="BLOCK_OW2_MENA_E"
netsh advfirewall firewall delete rule name="BLOCK_OW2_MENA_F"
netsh advfirewall firewall delete rule name="BLOCK_OW2_MENA_G"